// 官方 wujie 示例的路由清单（与探针 probe5 输出一致）。
// 同一份 manifest 对 official 与 taixu 两套实现都生效——差异体现在「实际渲染」层。
//
// 字段说明：
//   id: 唯一 ID（用作文件/key）
//   topLevel: 顶级菜单文本（用于点击展开）
//   sub: 子菜单文本（无 sub 表示直接顶级路由）
//   path: 路由路径（相对 base）
//   expected: 期望校验
//     - texts: 渲染后应出现的关键文本片段（任一命中即通过）
//     - appIds: 期望挂载的子应用 ID（official → shadowRoot; taixu → outlet）
//     - layout: 期望的布局计算样式断言（target 为元素 role）

const OFFICIAL_VUE = {
  label: 'official-vue',
  base: 'https://wujie-micro.github.io/demo-main-vue',
  entry: '/home',
  chrome: {
    toolbarTexts: ['文档', '仓库', 'react主应用', '预加载', '降级'],
    brandText: '无界',
    sloganText: '极致的微前端框架',
    featureColumns: ['极速', '强大', '简单'],
  },
  navWidth: 210,
  navFontSize: 20,
  navPad: '30px 0px',
  navItemHeight: 50,
  navItemPad: '10px 30px',
  routes: [
    { id: 'home', topLevel: '介绍', expected: { texts: ['无界', '极致的微前端框架', '极速', '强大', '简单'] } },
    { id: 'react16/home', topLevel: 'react16', sub: 'home', path: '/react16-sub/home', expected: { appIds: ['react16'], texts: ['react16示例', '当前react版本', '16.13.1', '当前antd版本', '4.18.3'] } },
    { id: 'react16/dialog', topLevel: 'react16', sub: '弹窗', path: '/react16-sub/dialog', expected: { appIds: ['react16'], texts: ['弹窗', '弹窗标题', '关闭', 'Open Modal', 'Modal'] } },
    { id: 'react16/location', topLevel: 'react16', sub: '路由', path: '/react16-sub/location', expected: { appIds: ['react16'], texts: ['路由', 'react16', 'state', 'search', '跳到', 'go'] } },
    { id: 'react16/communication', topLevel: 'react16', sub: '通信', path: '/react16-sub/communication', expected: { appIds: ['react16'], texts: ['通信', '向子应用传值', '基座修改值', 'jump', 'from'] } },
    { id: 'react16/nest', topLevel: 'react16', sub: '内嵌', path: '/react16-sub/nest', expected: { appIds: ['react16', 'react17'], texts: ['内嵌', '嵌入'] } },
    { id: 'react16/font', topLevel: 'react16', sub: '字体', path: '/react16-sub/font', expected: { appIds: ['react16'], texts: ['字体', 'font', 'font-family'] } },
    { id: 'react17/home', topLevel: 'react17', sub: 'home', path: '/react17-sub/home', expected: { appIds: ['react17'], texts: ['react17示例', '当前react版本', '17.0.2', '当前antd版本', '4.18.3'] } },
    { id: 'react17/dialog', topLevel: 'react17', sub: '弹窗', path: '/react17-sub/dialog', expected: { appIds: ['react17'], texts: ['弹窗'] } },
    { id: 'react17/location', topLevel: 'react17', sub: '路由', path: '/react17-sub/location', expected: { appIds: ['react17'], texts: ['路由'] } },
    { id: 'react17/communication', topLevel: 'react17', sub: '通信', path: '/react17-sub/communication', expected: { appIds: ['react17'], texts: ['通信'] } },
    { id: 'react17/state', topLevel: 'react17', sub: '状态', path: '/react17-sub/state', expected: { appIds: ['react17'], texts: ['状态', 'state', '0'] } },
    { id: 'vue2/home', topLevel: 'vue2', sub: 'home', path: '/vue2-sub/home', expected: { appIds: ['vue2'], texts: ['Vue2示例', '当前vue版本', '2.6.11', '当前element版本', '2.15.6'] } },
    { id: 'vue2/dialog', topLevel: 'vue2', sub: '弹窗', path: '/vue2-sub/dialog', expected: { appIds: ['vue2'], texts: ['弹窗'] } },
    { id: 'vue2/location', topLevel: 'vue2', sub: '路由', path: '/vue2-sub/location', expected: { appIds: ['vue2'], texts: ['路由'] } },
    { id: 'vue2/communication', topLevel: 'vue2', sub: '通信', path: '/vue2-sub/communication', expected: { appIds: ['vue2'], texts: ['通信'] } },
    { id: 'vue2/rich-text', topLevel: 'vue2', sub: '富文本', path: '/vue2-sub/rich-text', expected: { appIds: ['vue2'], texts: ['富文本', 'editor', '工具'] } },
    { id: 'vue3/home', topLevel: 'vue3', sub: 'home', path: '/vue3-sub/home', expected: { appIds: ['vue3'], texts: ['Vue3示例', '当前vue版本', '3.2.24', '当前element-plus版本', '2.2.6'] } },
    { id: 'vue3/dialog', topLevel: 'vue3', sub: '弹窗', path: '/vue3-sub/dialog', expected: { appIds: ['vue3'], texts: ['弹窗'] } },
    { id: 'vue3/location', topLevel: 'vue3', sub: '路由', path: '/vue3-sub/location', expected: { appIds: ['vue3'], texts: ['路由'] } },
    { id: 'vue3/contact', topLevel: 'vue3', sub: 'contact', path: '/vue3-sub/contact', expected: { appIds: ['vue3'], texts: ['contact', '联系人', 'phone', 'email'] } },
    { id: 'vue3/state', topLevel: 'vue3', sub: '状态', path: '/vue3-sub/state', expected: { appIds: ['vue3'], texts: ['状态', 'state'] } },
    { id: 'vue3/inline-event', topLevel: 'vue3', sub: 'inline-event', path: '/vue3-sub/inline-event', expected: { appIds: ['vue3'], texts: ['inline', '内联', 'event'] } },
    { id: 'vite/home', topLevel: 'vite', sub: 'home', path: '/vite-sub/home', expected: { appIds: ['vite'], texts: ['vue3 + vite示例', '当前vite版本', '2.7.2'] } },
    { id: 'vite/dialog', topLevel: 'vite', sub: '弹窗', path: '/vite-sub/dialog', expected: { appIds: ['vite'], texts: ['弹窗'] } },
    { id: 'vite/location', topLevel: 'vite', sub: '路由', path: '/vite-sub/location', expected: { appIds: ['vite'], texts: ['路由'] } },
    { id: 'vite/contact', topLevel: 'vite', sub: 'contact', path: '/vite-sub/contact', expected: { appIds: ['vite'], texts: ['contact'] } },
    { id: 'angular12', topLevel: 'angular12', path: '/angular12', expected: { appIds: ['angular12'], texts: ['angular', 'Angular'] } },
    { id: 'all', topLevel: 'all', path: '/all', expected: { appIds: ['react16', 'react17', 'vue2', 'vue3', 'vite', 'angular12'], texts: ['react16', 'react17', 'vue2', 'vue3', 'vite', 'angular'] } },
    { id: 'postmessage', topLevel: 'postmessage', path: '/postmessage', expected: { appIds: ['vue2'], texts: ['postmessage', 'hello', 'from'] } },
  ],
}

const OFFICIAL_REACT = {
  label: 'official-react',
  base: 'https://wujie-micro.github.io/demo-main-react',
  entry: '/#/home',
  chrome: {
    toolbarTexts: ['文档', '仓库', 'vue主应用', '预加载', '降级'],
    brandText: '无界',
    sloganText: '极致的微前端框架',
    featureColumns: ['极速', '强大', '简单'],
  },
  navWidth: 210,
  navFontSize: 20,
  navPad: '30px 0px',
  navItemHeight: 50,
  navItemPad: '10px 30px',
  routes: [
    { id: 'home', topLevel: '介绍', expected: { texts: ['无界', '极致的微前端框架'] } },
    { id: 'react16/home', topLevel: 'react16', sub: 'home', path: '/#/react16-sub/home', expected: { appIds: ['react16'], texts: ['react16示例', '当前react版本', '16.13.1'] } },
    { id: 'react16/dialog', topLevel: 'react16', sub: '弹窗', path: '/#/react16-sub/dialog', expected: { appIds: ['react16'], texts: ['弹窗'] } },
    { id: 'react16/location', topLevel: 'react16', sub: '路由', path: '/#/react16-sub/location', expected: { appIds: ['react16'], texts: ['路由'] } },
    { id: 'react16/communication', topLevel: 'react16', sub: '通信', path: '/#/react16-sub/communication', expected: { appIds: ['react16'], texts: ['通信'] } },
    { id: 'react16/nest', topLevel: 'react16', sub: '内嵌', path: '/#/react16-sub/nest', expected: { appIds: ['react16', 'react17'], texts: ['内嵌', '嵌入'] } },
    { id: 'react16/font', topLevel: 'react16', sub: '字体', path: '/#/react16-sub/font', expected: { appIds: ['react16'], texts: ['字体', 'font'] } },
    { id: 'react17/home', topLevel: 'react17', sub: 'home', path: '/#/react17-sub/home', expected: { appIds: ['react17'], texts: ['react17示例', '当前react版本', '17.0.2'] } },
    { id: 'react17/dialog', topLevel: 'react17', sub: '弹窗', path: '/#/react17-sub/dialog', expected: { appIds: ['react17'], texts: ['弹窗'] } },
    { id: 'react17/location', topLevel: 'react17', sub: '路由', path: '/#/react17-sub/location', expected: { appIds: ['react17'], texts: ['路由'] } },
    { id: 'react17/communication', topLevel: 'react17', sub: '通信', path: '/#/react17-sub/communication', expected: { appIds: ['react17'], texts: ['通信'] } },
    { id: 'react17/state', topLevel: 'react17', sub: '状态', path: '/#/react17-sub/state', expected: { appIds: ['react17'], texts: ['状态', 'state'] } },
    { id: 'vue2/home', topLevel: 'vue2', sub: 'home', path: '/#/vue2-sub/home', expected: { appIds: ['vue2'], texts: ['Vue2示例', '当前vue版本', '2.6.11'] } },
    { id: 'vue2/dialog', topLevel: 'vue2', sub: '弹窗', path: '/#/vue2-sub/dialog', expected: { appIds: ['vue2'], texts: ['弹窗'] } },
    { id: 'vue2/location', topLevel: 'vue2', sub: '路由', path: '/#/vue2-sub/location', expected: { appIds: ['vue2'], texts: ['路由'] } },
    { id: 'vue2/communication', topLevel: 'vue2', sub: '通信', path: '/#/vue2-sub/communication', expected: { appIds: ['vue2'], texts: ['通信'] } },
    { id: 'vue3/home', topLevel: 'vue3', sub: 'home', path: '/#/vue3-sub/home', expected: { appIds: ['vue3'], texts: ['Vue3示例', '当前vue版本', '3.2.24'] } },
    { id: 'vue3/dialog', topLevel: 'vue3', sub: '弹窗', path: '/#/vue3-sub/dialog', expected: { appIds: ['vue3'], texts: ['弹窗'] } },
    { id: 'vue3/location', topLevel: 'vue3', sub: '路由', path: '/#/vue3-sub/location', expected: { appIds: ['vue3'], texts: ['路由'] } },
    { id: 'vue3/contact', topLevel: 'vue3', sub: 'contact', path: '/#/vue3-sub/contact', expected: { appIds: ['vue3'], texts: ['contact'] } },
    { id: 'vue3/state', topLevel: 'vue3', sub: '状态', path: '/#/vue3-sub/state', expected: { appIds: ['vue3'], texts: ['状态', 'state'] } },
    { id: 'vue3/inline-event', topLevel: 'vue3', sub: 'inline-event', path: '/#/vue3-sub/inline-event', expected: { appIds: ['vue3'], texts: ['inline', '内联', 'event'] } },
    { id: 'vite/home', topLevel: 'vite', sub: 'home', path: '/#/vite-sub/home', expected: { appIds: ['vite'], texts: ['vue3 + vite示例', '当前vite版本', '2.7.2'] } },
    { id: 'vite/dialog', topLevel: 'vite', sub: '弹窗', path: '/#/vite-sub/dialog', expected: { appIds: ['vite'], texts: ['弹窗'] } },
    { id: 'vite/location', topLevel: 'vite', sub: '路由', path: '/#/vite-sub/location', expected: { appIds: ['vite'], texts: ['路由'] } },
    { id: 'vite/contact', topLevel: 'vite', sub: 'contact', path: '/#/vite-sub/contact', expected: { appIds: ['vite'], texts: ['contact'] } },
    { id: 'angular12', topLevel: 'angular12', path: '/#/angular12', expected: { appIds: ['angular12'], texts: ['angular', 'Angular'] } },
    { id: 'all', topLevel: 'all', path: '/#/all', expected: { appIds: ['react16', 'react17', 'vue2', 'vue3', 'vite', 'angular12'], texts: ['react16', 'react17', 'vue2', 'vue3', 'vite', 'angular'] } },
  ],
}

const TAIXU_VUE = {
  label: 'taixu-vue',
  base: 'https://taixu-micro.github.io/taixu/demo-wujie/hosts/main-vue',
  entry: '/',
  chrome: {
    toolbarTexts: ['文档', '仓库', '预加载', '降级'],
    brandText: 'taixu',
    sloganText: '官方示例集',
    featureColumns: ['极速', '强大', '简单'],
  },
  navWidth: 212,
  navFontSize: 18,
  navPad: '26px 0px',
  navItemHeight: 46,
  navItemPad: '10px 30px',
  routes: [
    { id: 'home', topLevel: '介绍', path: '/#/', expected: { texts: ['taixu', '官方示例集', '极速', '强大', '简单'] } },
    { id: 'react16/home', topLevel: 'react16', sub: 'home', path: '/#/react16-sub/home', expected: { appIds: ['react16'], texts: ['react16', '当前', 'react'] } },
    { id: 'react16/dialog', topLevel: 'react16', sub: '弹窗', path: '/#/react16-sub/dialog', expected: { appIds: ['react16'], texts: ['弹窗'] } },
    { id: 'react16/location', topLevel: 'react16', sub: '路由', path: '/#/react16-sub/location', expected: { appIds: ['react16'], texts: ['路由'] } },
    { id: 'react16/communication', topLevel: 'react16', sub: '通信', path: '/#/react16-sub/communication', expected: { appIds: ['react16'], texts: ['通信'] } },
    { id: 'react16/nest', topLevel: 'react16', sub: '内嵌', path: '/#/react16-sub/nest', expected: { appIds: ['react16', 'react17'], texts: ['内嵌', '嵌入'] } },
    { id: 'react16/font', topLevel: 'react16', sub: '字体', path: '/#/react16-sub/font', expected: { appIds: ['react16'], texts: ['字体', 'font'] } },
    { id: 'react17/home', topLevel: 'react17', sub: 'home', path: '/#/react17-sub/home', expected: { appIds: ['react17'], texts: ['react17', '当前', 'react'] } },
    { id: 'react17/dialog', topLevel: 'react17', sub: '弹窗', path: '/#/react17-sub/dialog', expected: { appIds: ['react17'], texts: ['弹窗'] } },
    { id: 'react17/location', topLevel: 'react17', sub: '路由', path: '/#/react17-sub/location', expected: { appIds: ['react17'], texts: ['路由'] } },
    { id: 'react17/communication', topLevel: 'react17', sub: '通信', path: '/#/react17-sub/communication', expected: { appIds: ['react17'], texts: ['通信'] } },
    { id: 'react17/state', topLevel: 'react17', sub: '状态', path: '/#/react17-sub/state', expected: { appIds: ['react17'], texts: ['状态', 'state'] } },
    { id: 'vue2/home', topLevel: 'vue2', sub: 'home', path: '/#/vue2-sub/home', expected: { appIds: ['vue2'], texts: ['vue2', '当前', 'vue', '2.'] } },
    { id: 'vue2/dialog', topLevel: 'vue2', sub: '弹窗', path: '/#/vue2-sub/dialog', expected: { appIds: ['vue2'], texts: ['弹窗'] } },
    { id: 'vue2/location', topLevel: 'vue2', sub: '路由', path: '/#/vue2-sub/location', expected: { appIds: ['vue2'], texts: ['路由'] } },
    { id: 'vue2/communication', topLevel: 'vue2', sub: '通信', path: '/#/vue2-sub/communication', expected: { appIds: ['vue2'], texts: ['通信'] } },
    { id: 'vue2/postmessage', topLevel: 'vue2', sub: 'postmessage', path: '/#/vue2-sub/postmessage', expected: { appIds: ['vue2'], texts: ['postmessage', 'hello', 'from'] } },
    { id: 'vue2/rich-text', topLevel: 'vue2', sub: '富文本', path: '/#/vue2-sub/rich-text', expected: { appIds: ['vue2'], texts: ['富文本', 'rich', 'editor'] } },
    { id: 'vue3/home', topLevel: 'vue3', sub: 'home', path: '/#/vue3-sub/home', expected: { appIds: ['vue3'], texts: ['vue3', '当前', 'vue', '3.'] } },
    { id: 'vue3/dialog', topLevel: 'vue3', sub: '弹窗', path: '/#/vue3-sub/dialog', expected: { appIds: ['vue3'], texts: ['弹窗'] } },
    { id: 'vue3/location', topLevel: 'vue3', sub: '路由', path: '/#/vue3-sub/location', expected: { appIds: ['vue3'], texts: ['路由'] } },
    { id: 'vue3/contact', topLevel: 'vue3', sub: 'contact', path: '/#/vue3-sub/contact', expected: { appIds: ['vue3'], texts: ['contact', '联系'] } },
    { id: 'vue3/state', topLevel: 'vue3', sub: '状态', path: '/#/vue3-sub/state', expected: { appIds: ['vue3'], texts: ['状态', 'state'] } },
    { id: 'vue3/inline-event', topLevel: 'vue3', sub: 'inline-event', path: '/#/vue3-sub/inline-event', expected: { appIds: ['vue3'], texts: ['inline', '内联', 'event'] } },
    { id: 'vue3/postmessage', topLevel: 'vue3', sub: 'postmessage', path: '/#/vue3-sub/postmessage', expected: { appIds: ['vue3'], texts: ['postmessage', 'hello', 'from'] } },
    { id: 'vite/home', topLevel: 'vite', sub: 'home', path: '/#/vite-sub/home', expected: { appIds: ['vite'], texts: ['vite', '当前', 'vue', '3.'] } },
    { id: 'vite/dialog', topLevel: 'vite', sub: '弹窗', path: '/#/vite-sub/dialog', expected: { appIds: ['vite'], texts: ['弹窗'] } },
    { id: 'vite/location', topLevel: 'vite', sub: '路由', path: '/#/vite-sub/location', expected: { appIds: ['vite'], texts: ['路由'] } },
    { id: 'vite/contact', topLevel: 'vite', sub: 'contact', path: '/#/vite-sub/contact', expected: { appIds: ['vite'], texts: ['contact'] } },
    { id: 'angular12', topLevel: 'angular12', path: '/#/angular12', expected: { appIds: ['angular12'], texts: ['angular', 'Angular'] } },
    { id: 'all', topLevel: 'multiple', path: '/#/multiple', expected: { appIds: ['react16', 'react17', 'vue2', 'vue3', 'vite', 'angular12'], texts: ['react16', 'react17', 'vue2', 'vue3', 'vite', 'angular'] } },
    { id: 'postmessage', topLevel: 'postmessage', path: '/#/postmessage', expected: { appIds: ['vue2'], texts: ['postmessage', 'hello', 'from'] } },
  ],
}

const TAIXU_REACT = {
  label: 'taixu-react',
  base: 'https://taixu-micro.github.io/taixu/demo-wujie/hosts/main-react',
  entry: '/',
  chrome: {
    toolbarTexts: ['文档', '仓库', '预加载', '降级'],
    brandText: 'taixu',
    sloganText: '官方示例集',
    featureColumns: ['极速', '强大', '简单'],
  },
  navWidth: 212,
  navFontSize: 18,
  navPad: '26px 0px',
  navItemHeight: 46,
  navItemPad: '10px 30px',
  routes: [
    { id: 'home', topLevel: '介绍', expected: { texts: ['taixu', '官方示例集', '极速', '强大', '简单'] } },
    { id: 'react16/home', topLevel: 'react16', sub: 'home', path: '/#/react16-sub/home', expected: { appIds: ['react16'], texts: ['react16', '当前', 'react'] } },
    { id: 'react16/dialog', topLevel: 'react16', sub: '弹窗', path: '/#/react16-sub/dialog', expected: { appIds: ['react16'], texts: ['弹窗'] } },
    { id: 'react16/location', topLevel: 'react16', sub: '路由', path: '/#/react16-sub/location', expected: { appIds: ['react16'], texts: ['路由'] } },
    { id: 'react16/communication', topLevel: 'react16', sub: '通信', path: '/#/react16-sub/communication', expected: { appIds: ['react16'], texts: ['通信'] } },
    { id: 'react17/home', topLevel: 'react17', sub: 'home', path: '/#/react17-sub/home', expected: { appIds: ['react17'], texts: ['react17', '当前', 'react'] } },
    { id: 'react17/dialog', topLevel: 'react17', sub: '弹窗', path: '/#/react17-sub/dialog', expected: { appIds: ['react17'], texts: ['弹窗'] } },
    { id: 'react17/location', topLevel: 'react17', sub: '路由', path: '/#/react17-sub/location', expected: { appIds: ['react17'], texts: ['路由'] } },
    { id: 'react17/communication', topLevel: 'react17', sub: '通信', path: '/#/react17-sub/communication', expected: { appIds: ['react17'], texts: ['通信'] } },
    { id: 'react17/state', topLevel: 'react17', sub: '状态', path: '/#/react17-sub/state', expected: { appIds: ['react17'], texts: ['状态', 'state'] } },
    { id: 'vue2/home', topLevel: 'vue2', sub: 'home', path: '/#/vue2-sub/home', expected: { appIds: ['vue2'], texts: ['vue2', '当前', 'vue', '2.'] } },
    { id: 'vue2/dialog', topLevel: 'vue2', sub: '弹窗', path: '/#/vue2-sub/dialog', expected: { appIds: ['vue2'], texts: ['弹窗'] } },
    { id: 'vue2/location', topLevel: 'vue2', sub: '路由', path: '/#/vue2-sub/location', expected: { appIds: ['vue2'], texts: ['路由'] } },
    { id: 'vue2/communication', topLevel: 'vue2', sub: '通信', path: '/#/vue2-sub/communication', expected: { appIds: ['vue2'], texts: ['通信'] } },
    { id: 'vue2/postmessage', topLevel: 'vue2', sub: 'postmessage', path: '/#/vue2-sub/postmessage', expected: { appIds: ['vue2'], texts: ['postmessage', 'hello', 'from'] } },
    { id: 'vue2/rich-text', topLevel: 'vue2', sub: '富文本', path: '/#/vue2-sub/rich-text', expected: { appIds: ['vue2'], texts: ['富文本', 'rich', 'editor'] } },
    { id: 'vue3/home', topLevel: 'vue3', sub: 'home', path: '/#/vue3-sub/home', expected: { appIds: ['vue3'], texts: ['vue3', '当前', 'vue', '3.'] } },
    { id: 'vue3/dialog', topLevel: 'vue3', sub: '弹窗', path: '/#/vue3-sub/dialog', expected: { appIds: ['vue3'], texts: ['弹窗'] } },
    { id: 'vue3/location', topLevel: 'vue3', sub: '路由', path: '/#/vue3-sub/location', expected: { appIds: ['vue3'], texts: ['路由'] } },
    { id: 'vue3/contact', topLevel: 'vue3', sub: 'contact', path: '/#/vue3-sub/contact', expected: { appIds: ['vue3'], texts: ['contact', '联系'] } },
    { id: 'vue3/state', topLevel: 'vue3', sub: '状态', path: '/#/vue3-sub/state', expected: { appIds: ['vue3'], texts: ['状态', 'state'] } },
    { id: 'vue3/inline-event', topLevel: 'vue3', sub: 'inline-event', path: '/#/vue3-sub/inline-event', expected: { appIds: ['vue3'], texts: ['inline', '内联', 'event'] } },
    { id: 'vite/home', topLevel: 'vite', sub: 'home', path: '/#/vite-sub/home', expected: { appIds: ['vite'], texts: ['vite', '当前', 'vue', '3.'] } },
    { id: 'vite/dialog', topLevel: 'vite', sub: '弹窗', path: '/#/vite-sub/dialog', expected: { appIds: ['vite'], texts: ['弹窗'] } },
    { id: 'vite/location', topLevel: 'vite', sub: '路由', path: '/#/vite-sub/location', expected: { appIds: ['vite'], texts: ['路由'] } },
    { id: 'vite/contact', topLevel: 'vite', sub: 'contact', path: '/#/vite-sub/contact', expected: { appIds: ['vite'], texts: ['contact'] } },
    { id: 'angular12', topLevel: 'angular12', path: '/#/angular12', expected: { appIds: ['angular12'], texts: ['angular', 'Angular'] } },
    { id: 'all', topLevel: 'all', path: '/#/all', expected: { appIds: ['react16', 'react17', 'vue2', 'vue3', 'vite', 'angular12'], texts: ['react16', 'react17', 'vue2', 'vue3', 'vite', 'angular'] } },
  ],
}

export const TARGETS = {
  'official-vue': OFFICIAL_VUE,
  'official-react': OFFICIAL_REACT,
  'taixu-vue': TAIXU_VUE,
  'taixu-react': TAIXU_REACT,
}
